### PR TITLE
HTML/CSS Project 7: Using Bootstrap

### PR DESCRIPTION
**Pull request by Osong-Michael**
## This project was done using bootstrap and my own personal touch.
- To achieve the responsive design I used the Bootstrap .col, .sm, .md, .lg classes to display sections of the page differently at different screen sizes.
- Also, I added my own styles and media queries to make sections of the navbar disappear at various screen sizes since I couldn't achieve this with Bootstrap. 
- I also wanted to challenge myself to do more with this project so I tried my best to replicate the design aspects of each section as close to the original as I could get.

### CODE REVIEW

**Comment by Osong-Michael** [comment]
> [`_`](

- 

- [ ] #1. url

)

**Comment by lekegitrepo** [comment]
### Hi @OA7 👏 💪 
### _You have done an excellent job, the page looks great. However, there are a few requirements you still need to add before the project can be approved._

**_1. The Sign in on the navbar should be a link_** ([link to page](https://www.newsweek.com/))

**_2. Try to fix this section 👇 
Large screen:_**
image

**_Put space between the contents like the original:_**

image

**_Implement the changes and submit for review_**

**_If you have any doubt or question contact me on slack_**

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Great Job @OA7  👏👏

You've done quite well on this project. 🎉

However, there are a few areas that need to be addressed before proceeding: 👇

- [ ] Required - Kindly remove all inline styles in your HTML. Make sure that basic CSS bad practices are not used read through this [article for support ](https://speckyboy.com/good-bad-css-practices) and [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright.

- [ ] Required - Also remove all comments existing on your HTML file.

Kindly fix the required changes and submit another review request.
Feel free to reach out to me on slack(michgolden) if you need further clarification.

HAPPY CODING 👨‍💻

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @OA7, congratulations on this project and working so hard with other TSE's to make your project better 😄 Your project now meets the minimum requirements, I hereby approve your project :+1: Kindly merge to master and submit the project completion form.

Good luck with your next submissions ✋ 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Pull request merged**
